### ISSUE TITLE
Different screen sizes make me go AoA

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/svg-icon-sets#1]
@hellachella
@HannahDelaney
@MacKenzieRose

Hi, I got trouble with making the matching screen sizes. I think that the problem is in the grid but I cannot solve it. Please help me ;-;

**Comment by hellachella** [comment]
Hi Sam! Ok, so try using `grid-template-areas` in your `section` and setting up your grid that way:

```
section {
  display: grid;
  grid-template-areas: "intro" "col1" "col2" "col3";
  gap: /* you decide! */
  padding: /* you decide! */
  background-color: /* you decide! */
  background-image: /* you decide! */  
  color: /* you decide! */;
}
```

Put the background gradient into the `section` rather than in the `body`. The `body` should only contain `margin: 0;`

**Comment by hellachella** [comment]
I think you will also have an easier time if you take your icons out of the `ul` and just put them each in their own div.  

It does make sense to put cards with the icon and information into a `ul`, so I see what you were thinking, but for the purpose of this assignment, they will be in `divs`.  li will mess up all your padding and stuff and have a bunch of rules about wrapping, so in the interest of avoiding having to add a bunch of reset CSS and adjustments, it will be easier to just make them into `divs`.
